<a href="https://colab.research.google.com/github/Sjing2/SJ_project/blob/master/%5B%EB%A7%88%EC%BC%80%ED%8C%85%20%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%5D%20%EC%8B%9C%EC%9E%A5%20%EB%B6%84%EC%84%9D%EC%9D%84%20%EC%9C%84%ED%95%9C%20%ED%85%8D%EC%8A%A4%ED%8A%B8%20%EB%B0%8F%20%EC%BB%A4%EB%AE%A4%EB%8B%88%ED%8B%B0%20%EB%A7%88%EC%9D%B4%EB%8B%9D%20%EA%B8%B0%EB%B0%98%20%EC%9D%B8%EC%8A%A4%ED%83%80%EA%B7%B8%EB%9E%A8%20%EC%82%AC%EC%9A%A9%EC%9E%90%20%ED%94%84%EB%A1%9C%ED%8C%8C%EC%9D%BC%EB%A7%81/2.%20Preprocessing/9.%5B%EC%A0%84%EC%B2%98%EB%A6%AC%5D%20Post%20Add%20shortcode_%EC%99%84%EB%A3%8C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive/

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
word_df = pd.read_csv('/content/gdrive/My Drive/프로젝트/word_again/word_df.csv')

In [ ]:
word_df

       Unnamed: 0  ...                                          next_page
0               0  ...  https://www.instagram.com/graphql/query/?query...
1               1  ...  https://www.instagram.com/graphql/query/?query...
2               2  ...  https://www.instagram.com/graphql/query/?query...
3               3  ...  https://www.instagram.com/graphql/query/?query...
4               4  ...  https://www.instagram.com/graphql/query/?query...
...           ...  ...                                                ...
22370       22370  ...  https://www.instagram.com/graphql/query/?query...
22371       22371  ...  https://www.instagram.com/graphql/query/?query...
22372       22372  ...  https://www.instagram.com/graphql/query/?query...
22373       22373  ...  https://www.instagram.com/graphql/query/?query...
22374       22374  ...  https://www.instagram.com/graphql/query/?query...

[22375 rows x 14 columns]

In [ ]:
shortcode_df = pd.read_csv('/content/gdrive/My Drive/프로젝트/word_again/shortcode_df.csv')

In [ ]:
shortcode_df

       Unnamed: 0    shortcode
0               0  CEasJz1JPgQ
1               1  CEY3iR2pr-l
2               2  CEYOgJUJ1KR
3               3  CEWyKvgJE1C
4               4  CEWde7hJDk1
...           ...          ...
22370       22370  CDd8XJ4Fm3Y
22371       22371  CDd7qDAlaO3
22372       22372  CDd7U1IFXCu
22373       22373  CDd60iUlSIr
22374       22374  CDdjlfqlZEf

[22375 rows x 2 columns]

In [ ]:
add_df = pd.merge(word_df, shortcode_df, on = "Unnamed: 0")

In [ ]:
add_df.head(1)

   Unnamed: 0  ...    shortcode
0           0  ...  CEasJz1JPgQ

[1 rows x 15 columns]

In [ ]:
add_df = add_df[['Unnamed: 0', 'shortcode','insta_id', 'inner_id', 'post_date', 'url', 'content', 'media_url', 'hashtag', 'region_tag', 'like_count', 'view_count', 'crawling_time', 'team_idx', 'next_page']]
add_df

       Unnamed: 0  ...                                          next_page
0               0  ...  https://www.instagram.com/graphql/query/?query...
1               1  ...  https://www.instagram.com/graphql/query/?query...
2               2  ...  https://www.instagram.com/graphql/query/?query...
3               3  ...  https://www.instagram.com/graphql/query/?query...
4               4  ...  https://www.instagram.com/graphql/query/?query...
...           ...  ...                                                ...
22370       22370  ...  https://www.instagram.com/graphql/query/?query...
22371       22371  ...  https://www.instagram.com/graphql/query/?query...
22372       22372  ...  https://www.instagram.com/graphql/query/?query...
22373       22373  ...  https://www.instagram.com/graphql/query/?query...
22374       22374  ...  https://www.instagram.com/graphql/query/?query...

[22375 rows x 15 columns]

In [ ]:
add_df.drop(['Unnamed: 0'], axis='columns', inplace=True)
add_df

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

         shortcode  ...                                          next_page
0      CEasJz1JPgQ  ...  https://www.instagram.com/graphql/query/?query...
1      CEY3iR2pr-l  ...  https://www.instagram.com/graphql/query/?query...
2      CEYOgJUJ1KR  ...  https://www.instagram.com/graphql/query/?query...
3      CEWyKvgJE1C  ...  https://www.instagram.com/graphql/query/?query...
4      CEWde7hJDk1  ...  https://www.instagram.com/graphql/query/?query...
...            ...  ...                                                ...
22370  CDd8XJ4Fm3Y  ...  https://www.instagram.com/graphql/query/?query...
22371  CDd7qDAlaO3  ...  https://www.instagram.com/graphql/query/?query...
22372  CDd7U1IFXCu  ...  https://www.instagram.com/graphql/query/?query...
22373  CDd60iUlSIr  ...  https://www.instagram.com/graphql/query/?query...
22374  CDdjlfqlZEf  ...  https://www.instagram.com/graphql/query/?query...

[22375 rows x 14 columns]

In [ ]:
add_df.to_csv("/content/gdrive/My Drive/프로젝트/word_again/cc_word_add.csv")