<a href="https://colab.research.google.com/github/Sjing2/SJ_project/blob/master/%5B%EB%A7%88%EC%BC%80%ED%8C%85%20%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%5D%20%EC%8B%9C%EC%9E%A5%20%EB%B6%84%EC%84%9D%EC%9D%84%20%EC%9C%84%ED%95%9C%20%ED%85%8D%EC%8A%A4%ED%8A%B8%20%EB%B0%8F%20%EC%BB%A4%EB%AE%A4%EB%8B%88%ED%8B%B0%20%EB%A7%88%EC%9D%B4%EB%8B%9D%20%EA%B8%B0%EB%B0%98%20%EC%9D%B8%EC%8A%A4%ED%83%80%EA%B7%B8%EB%9E%A8%20%EC%82%AC%EC%9A%A9%EC%9E%90%20%ED%94%84%EB%A1%9C%ED%8C%8C%EC%9D%BC%EB%A7%81/5_%5B%EC%A0%84%EC%B2%98%EB%A6%AC%5D_Delete_Follower1000_Like1000.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive/

In [ ]:
import re
import pandas as pd
import os

In [ ]:
os.chdir('/content/gdrive/My Drive/인스타그램_프로파일링/Post')
new_df = pd.read_csv('cc_hangul.csv')

In [ ]:
new_df

         shortcode  ...                                          next_page
0      CEasJz1JPgQ  ...  https://www.instagram.com/graphql/query/?query...
1      CEY3iR2pr-l  ...  https://www.instagram.com/graphql/query/?query...
2      CEYOgJUJ1KR  ...  https://www.instagram.com/graphql/query/?query...
3      CEWyKvgJE1C  ...  https://www.instagram.com/graphql/query/?query...
4      CEWde7hJDk1  ...  https://www.instagram.com/graphql/query/?query...
...            ...  ...                                                ...
36680  CDd8XJ4Fm3Y  ...  https://www.instagram.com/graphql/query/?query...
36681  CDd7qDAlaO3  ...  https://www.instagram.com/graphql/query/?query...
36682  CDd7U1IFXCu  ...  https://www.instagram.com/graphql/query/?query...
36683  CDd60iUlSIr  ...  https://www.instagram.com/graphql/query/?query...
36684  CDdjlfqlZEf  ...  https://www.instagram.com/graphql/query/?query...

[36685 rows x 14 columns]

In [ ]:
over1000_df = pd.read_csv('/content/gdrive/My Drive/인스타그램_프로파일링/Relation(start, end)/cc_over1000.csv')

In [ ]:
over1000_df

    Unnamed: 0         data
0            0  23898132889
1            1   7159109885
2            2   7798342681
3            3  38063234978
4            4   3043715720
5            5   2525851289
6            6  31785307735
7            7   6813567329
8            8  13317184033
9            9   7459407725
10          10  12868701287
11          11  21729607473

In [ ]:
def del_over1000(df, over1000_df):
    # 팔로워 1000명 이상 id 제외
    for over1000_id in list(over1000_df['data']):
        idx = df[df['insta_id']==over1000_id].index
        df.drop(idx, inplace=True)
    
    # 좋아요 1000개 이상 게시물 있는 id 제외
    df['like_count'] = df['like_count'].apply(int)
    id_lst = list(set(df['insta_id']))
    for user_id in id_lst:
        count = 0
        for y in list(df[df['insta_id']==user_id]['like_count']):
            if y > 1000:
                count += 1
        if count > 1:
            idx = df[df['insta_id']==user_id].index
            df.drop(idx, inplace=True)
            
    return df

In [ ]:
new_new_df = del_over1000(new_df, over1000_df)

In [ ]:
new_new_df

         shortcode  ...                                          next_page
0      CEasJz1JPgQ  ...  https://www.instagram.com/graphql/query/?query...
1      CEY3iR2pr-l  ...  https://www.instagram.com/graphql/query/?query...
2      CEYOgJUJ1KR  ...  https://www.instagram.com/graphql/query/?query...
3      CEWyKvgJE1C  ...  https://www.instagram.com/graphql/query/?query...
4      CEWde7hJDk1  ...  https://www.instagram.com/graphql/query/?query...
...            ...  ...                                                ...
36680  CDd8XJ4Fm3Y  ...  https://www.instagram.com/graphql/query/?query...
36681  CDd7qDAlaO3  ...  https://www.instagram.com/graphql/query/?query...
36682  CDd7U1IFXCu  ...  https://www.instagram.com/graphql/query/?query...
36683  CDd60iUlSIr  ...  https://www.instagram.com/graphql/query/?query...
36684  CDdjlfqlZEf  ...  https://www.instagram.com/graphql/query/?query...

[33201 rows x 14 columns]

In [ ]:
id_lst = list(set(new_new_df['insta_id']))
len(id_lst)

1578

In [ ]:
new_df.to_csv('/content/gdrive/My Drive/인스타그램_프로파일링/Post/Delete(foreign, over1000)/cc_delete.csv', index=False)